apiVersion: v1
kind: Secret
metadata:
  name: docker-registry-secret
  labels:
    {{- include "website.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "10"
    "helm.sh/hook-delete-policy": before-hook-creation
data:
  .dockerconfigjson: {{ .Values.image.dockerconfigjson }}
type: kubernetes.io/dockerconfigjson
